# Generated by Django 2.1.3 on 2018-11-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(max_length=200)),
                ('select', models.CharField(max_length=200)),
                ('having', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=200)),
                ('sort', models.CharField(max_length=200)),
                ('where', models.CharField(max_length=200)),
                ('nestedSelect', models.CharField(max_length=200)),
            ],
        ),
    ]
