# Generated by Django 2.1.3 on 2018-11-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ESTABLECIMIENTO', models.CharField(max_length=25)),
                ('INSTITUCION', models.CharField(max_length=25)),
                ('LICENCIA', models.CharField(max_length=25)),
                ('LICENCIA_FECHA_EXPEDICION', models.CharField(max_length=25)),
                ('ENTIDAD_FEDERATIVA', models.CharField(max_length=25)),
                ('CODIGO_ENTIDAD_FEDERATIVA', models.IntegerField()),
                ('PROCURACION', models.BooleanField(default=False)),
                ('TRASPLANTE_AMNIOS', models.BooleanField(default=False)),
                ('TRASPLANTE_CARA', models.BooleanField(default=False)),
                ('TRASPLANTE_CELULAS_PANCREATICAS', models.BooleanField(default=False)),
                ('TRASPLANTE_CORAZON', models.BooleanField(default=False)),
                ('TRASPLANTE_CORNEA', models.BooleanField(default=False)),
                ('TRASPLANTE_EXTREMIDADES', models.BooleanField(default=False)),
                ('TRASPLANTE_HUESO', models.BooleanField(default=False)),
                ('TRASPLANTE_INTESTINO', models.BooleanField(default=False)),
                ('TRASPLANTE_MANO', models.BooleanField(default=False)),
                ('TRASPLANTE_PANCREAS', models.BooleanField(default=False)),
                ('TRASPLANTE_PARATIROIDES', models.BooleanField(default=False)),
                ('TRASPLANTE_PIEL', models.BooleanField(default=False)),
                ('TRASPLANTE_PULMON', models.BooleanField(default=False)),
                ('TRASPLANTE_RIÑON', models.BooleanField(default=False)),
                ('TRASPLANTE_VALVULAS', models.BooleanField(default=False)),
                ('BANCO_AMNIOS', models.BooleanField(default=False)),
                ('BANCO_CORNEA', models.BooleanField(default=False)),
                ('BANCO_HUESO', models.BooleanField(default=False)),
                ('BANCO_PIEL', models.BooleanField(default=False)),
            ],
        ),
    ]
