# Generated by Django 2.1.3 on 2018-11-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_establecimientos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='establecimientos',
            old_name='TRASPLANTE_RIÑON',
            new_name='TRASPLANTE_RINON',
        ),
    ]
